name: AdvancedSurvivalPlugin
version: '${project.version}'
main: fr.swansky.advancedsurvivalplugin.AdvancedSurvivalPlugin
api-version: 1.17
authors: [ Swansky ]
description: Plugin for Swansky server
commands:
  customItem:
    description: give custom item
    usage: /customItem <type>
  addMarket:
    description: addMarket
    usage: /addMarket <unique id> <market title>
  addVillagerMarket:
    description:  add villager market
    usage: /addVillagerMarket <market id>
  deleteMarket:
    description: delete market
    usage: /deleteMarket <market id>
  marketList:
    description: list all market
    usage: /marketList
  addMarketItem:
    description: add item to market
    usage: /addMarketItem <ID> <MATERIAL icon> <sellable> <sell price> <purchasable>  <purchase price>  <Display name>
  openMarket:
    description: Open market with market id
    usage: /openMarket <marketID>
